apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrosa-crypto-strategy-ta
  namespace: petrosa-apps
  labels:
    app: petrosa-crypto-strategy-ta-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nosql-petrosa-binance
  template:
    metadata:
      labels:
        app: nosql-petrosa-binance
    spec:
      containers:
      - name: nosql-petrosa-binance
        image: yurisa2/petrosa-crypto-strategy-ta:v0.0.9
        imagePullPolicy: Always
        env:
          - name: VERSION
            value: "0.0.9"
          - name: KAFKA_SUBSCRIBER
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: KAFKA_SUBSCRIBER
                optional: false
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: MONGO_URI
                optional: false
                - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
                optional: false
          - name: OTEL_EXPORTER_OTLP_METRIC_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: OTEL_EXPORTER_OTLP_METRIC_ENDPOINT
                optional: false
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: petrosa-apps-secret
                key: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                optional: false

          - name: OTEL_SERVICE_NAME
            value: "petrosa-crypto-strategy-ta"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_METRICS_EXPORTER
            value: "otlp"
          - name: OTEL_LOGS_EXPORTER
            value: "otlp"
          - name: OTEL_PYTHON_LOG_CORRELATION
            value: "true"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
          - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
            value: "true"
          - name: OTEL_EXPORTER_OTLP_LOGS_INSECURE
            value: "true"
          - name: OTEL_EXPORTER_OTLP_METRICS_INSECURE
            value: "true"
          - name: OTEL_EXPORTER_OTLP_METRIC_INSECURE
            value: "true"
          - name: OTEL_EXPORTER_OTLP_SPAN_INSECURE
            value: "true"
          - name: OTEL_METRIC_EXPORT_INTERVAL
            value: "5"
      restartPolicy: Always
         